# Generated by Django 6.0.3 on 2026-04-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationhistory',
            name='suno_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
