# Generated by Django 6.0.3 on 2026-04-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_generationhistory_suno_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationhistory',
            name='style_used',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
