import type { Metadata } from 'next';
import { Geist_Mono, Young_Serif } from 'next/font/google';
import './globals.css';
import { NavBar } from '../components/Navbar';
import { SessionProvider } from '../components/SessionProvider';


const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});


const youngSerif = Young_Serif({
	weight: '400',
	variable: '--font-young-serif',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${youngSerif.variable} ${geistMono.variable} font-(family-name:--font-young-serif) antialiased`}
			>
				<SessionProvider>
					<NavBar />
					{children}
				</SessionProvider>
			</body>
		</html>
	);
}
