from typing import Protocol, runtime_checkable


@runtime_checkable
class SunoService(Protocol):
    def submit_generation(self, prompt: str, style: str, title: str, instrumental: bool, api_key: str) -> str: ...
    def fetch_task_result(self, task_id: str) -> dict: ...
    def fetch_credits(self) -> int: ...
